---
- name: Laravel | Check if Composer is installed
  raw: composer
  register: composer_installed
  ignore_errors: true

#- name: Laravel | Install Composer
#  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
#  when: composer_installed.stdout.find('command not found') != -1
#  become: yes
