---
- name: Laravel | Add php-7.1 PPA
  apt_repository: repo='ppa:ondrej/php'
                  state=present
                  update_cache=yes
  become: yes

- name: Laravel | install php packages
  apt: pkg={{ item }} state=present
  with_items:
    - php7.1-fpm
    - php7.1-cli
    - php7.1-common
    - php7.1-curl
    - php7.1-json
    - php7.1-gd
    - php7.1-mcrypt
    - php7.1-odbc
    - php7.1-pgsql
    - php7.1-mbstring
    - php7.1-mysql
    - php7.1-xmlrpc
    - php7.1-opcache
    - php7.1-intl
    - php7.1-bz2
    - php7.1-xml
  become: yes

- name: Laravel | FPM php.ini
  template:
    src=php.ini.j2
    dest=/etc/php/7.1/fpm/php.ini
    backup=yes
    owner=root
    group=root
    mode=0644
  become: yes

- name: Laravel | CLI php.ini
  template:
    src=php.ini.j2
    dest=/etc/php/7.1/cli/php.ini
    backup=yes
    owner=root
    group=root
    mode=0644
  become: yes

- name: Laravel | configure opcache
  template:
    src=opcache.init.j2
    dest=/etc/php/7.1/mods-available/opcache.ini
    backup=yes
    owner=root
    group=root
    mode=0644
  become: yes

- name: Laravel | restart nginx
  raw: service nginx restart
  become: yes

- name: Laravel | restart fpm
  raw: service php7.1-fpm restart
  become: yes
