---
- name: Update system
  apt:
    update_cache: yes

- name: Install Python3
  apt:
    name:
      - python3
      - python3-pip
      - python3-setuptools
      - python-pip
      - python-setuptools

- name: Install MySQL Server
  apt:
    name: default-mysql-server
    update_cache: yes

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Install PyMySQL
  pip:
    name: pymysql
    executable: pip3.7

- name: Create DB
  mysql_db:
    name: devops
    state: present
    login_user: root
    login_password: ''

- name: Config User MySQL
  mysql_user:
    name: root
    login_user: root
    login_password: ''
    password: mysqlpwd
    priv: "*.*:ALL,GRANT"