---
- name: Install
  become: yes
  apt: name=nginx state=latest

- name: Start
  become: yes
  service: name=nginx state=started enabled=true

- name: Delete default.conf
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: nginx reload

- name: Configure domains
  include: site.yml
  with_items:
    - { name: 'tek.ganster-dev.fr', port: 5000 }
    - { name: 'api.tek.ganster-dev.fr', port: 5001 }